### ISSUE TITLE
update token list

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-js#113]
Can we update our token list to the full list of tokens currently available?

Current list:
https://github.com/gnosis/dex-js/blob/master/src/tokenList.json

I am asking for it since I would like this token data in dex-visulaltion-tools?

**Comment by josojo** [comment]
@anxolin If I would update the whole list, would it break something? would we get automatically all tokens listed in the front-end?

**Comment by josojo** [comment]
And we should change the structure of the id;
a token with id x in mainnet does not need to have the same id on rinkeby

**Comment by anxolin** [comment]
Sorry @josojo I missed this PR. I'm not caught up with my mail, and I just reviewed the pending PRs (didn't see this issue).

If we update the list, we will add the tokens to the interface. I'm not sure if we want that. We could ask Martin.

Anyways, I think that for the tool you mentioned, it would be ideal to use the graph. This way you'll always be updated.

**Comment by josojo** [comment]
Sounds good. I will try out the theGraph solution!

**Comment by anxolin** [comment]
Let me know if u need any help with that :)

**Comment by anxolin** [comment]
Hei @josojo I think this issue is closed already, we:
- Included all missing tokens
- New version in the web now allows to use any token

Closing... please, re-open if it's not solved
