### ISSUE TITLE
Incorrect Token IDs from tokenList.json

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-js#88]
The following two tokens have incorrect IDs:

https://github.com/gnosis/dex-js/blob/0d93c1c36f0323b693add5a4697b2cbd585e1b23/src/tokenList.json#L120-L143

Token 11: is WBTC
Token 12: is SAI

**Comment by anxolin** [comment]
Hei @bh2smith , maybe I'm checking sth wrong, but it looks they are ok:

* sETH: https://etherscan.io/address/0x5e74C9036fb86BD7eCdcb084a0673EFc32eA31cb
* OWL: https://etherscan.io/address/0x1A5F9352Af8aF974bFC03399e3767DF6370d82e4

**Comment by bh2smith** [comment]
Owl has token id zero. And the wrong toke n is listed here at id 11. I am away from keys at the moment. But I can show you the token addresses in correspondence with the token ids on the contract in a moment.

**Comment by anxolin** [comment]
Aha, ok. This is important. Thanks for notifying!
